AIUTS/urls.py
from django.urls import path
from . import views

app_name = 'AIUTS'
urlpatterns = [
    path('', views.userAccountList.as_view(), name='index'),
    path('acc/<str:pk>/', views.userbalanceView.as_view(), name='userbalance'),
    path('transactionList/', views.transactionList.as_view(), name='transactionList'),
    path('requestList/', views.requestList.as_view(), name='requestList'),
    path('pendingList/', views.pendingList.as_view(), name='pendingList'),
    path('Approve/<int:pk>', views.Approve.as_view(), name='Approve'),
    path('addAccount/', views.CreateAccountView.as_view(), name='addAccount'),
    path('addTransaction/', views.CreateTransactionView.as_view(), name='addTransaction'),
    path('paymentRequest/', views.makeRequest.as_view(), name='paymentRequest'),
    path('deposit/', views.makeDeposit.as_view(), name="deposit"),
]

AiuTransactionSystem/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('AIUTS.urls')),
    path('controller/', include('controller.urls'))
]

AIUTS/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from django.db.models.signals import post_save
from django.dispatch import receiver

class UserAccount(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    accountId = models.CharField(primary_key=True,max_length=255,)
    accountAmount = models.IntegerField(default=100)

    def __str__(self):
        return f"{self.user}"

    '''
    everytime the user is create, it will add to a users group directly
    '''
    @receiver(post_save, sender=User)
    def create_account(sender, instance, created, **kwargs):
        if created:
            print(User.username)
            # UserAccount.objects.create(user=instance)
            print('User create')
            instance.groups.add(Group.objects.get(name='users'))
            print('User add to group')
            

    # post_save.connect(create_account, sender=User)


class UserTransaction(models.Model):
    STATUS = (('Pending', 'Pending'),('Approve', 'Approve'))
    transactionId = models.AutoField(primary_key=True)
    transactionTime = models.DateTimeField(auto_now_add=True)
    transactionSender = models.ForeignKey(UserAccount, on_delete=models.CASCADE, related_name="Sender")
    transactionReceiver = models.ForeignKey(UserAccount, on_delete=models.CASCADE, related_name="Receiver")
    transactionAmount = models.IntegerField(default=0)
    transactionMessage = models.CharField(max_length=100, null=True)
    transactionStatus =  models.CharField(max_length=20, choices=STATUS, default=STATUS[0][0])
    
    def __str__ (self):
        return "{}".format(self.transactionTime)

    def save(self, *args, **kwargs):
        if self.transactionStatus == 'Approve':
            print("Approve")

            self.transactionSender.accountAmount -= self.transactionAmount
            self.transactionSender.save()
            self.transactionReceiver.accountAmount += self.transactionAmount
            self.transactionReceiver.save()

            super(UserTransaction, self).save(*args, **kwargs)

        if self.transactionStatus == 'Pending':
            print("pending")
            super(UserTransaction, self).save(*args, **kwargs)

class DepositRequest(models.Model):
    STATUS = (
			('Pending', 'Pending'),
			('Approve', 'Approve')
		)
    DepositRequestID = models.AutoField(primary_key=True)
    RequestTime = models.DateTimeField(auto_now_add=True)
    RequestReceiver = models.ForeignKey(UserAccount, on_delete=models.CASCADE, related_name="RequestReceiver")
    RequestAmount = models.IntegerField(default=100)
    RequestStatus =  models.CharField(max_length=20, choices=STATUS, default=STATUS[0][0])

    def __str__(self):
        return f"{self.RequestReceiver}"

    def save(self, *args, **kwargs):
        if self.RequestStatus == 'Approve':
            self.RequestReceiver.accountAmount += self.RequestAmount
            self.RequestReceiver.save()

            super(DepositRequest, self).save(*args, **kwargs)
        if self.RequestStatus == 'Pending':
            super(DepositRequest, self).save(*args, **kwargs)



        
   

AIUTS/forms.py
from django.forms import ModelForm
from .models import UserTransaction, UserAccount, DepositRequest
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class CreateAccount(UserCreationForm):
    # password = forms.CharField(widget = forms.PasswordInput, error_messages = {'required':"Please create a password"})
    # # accountAmount =forms.IntegerField(error_messages = {'required':"Please provide a starting amount for your account"})
    # username = forms.CharField(error_messages = {'required':"Please enter your username"})
    class Meta:
        model = User
        fields = ['username','password1','password2'] 

class CreateTransaction(forms.ModelForm):
    class Meta:
        model = UserTransaction
        fields =['transactionReceiver','transactionAmount','transactionMessage'] 

class DepositRequestForm(forms.ModelForm):
    class Meta:
        model = DepositRequest
        fields =['RequestAmount']

AIUTS/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import messages
from django.utils import timezone
from django.views import generic
from django.urls import reverse
from datetime import datetime, timedelta
from .models import UserAccount, UserTransaction, DepositRequest
from .forms import CreateAccount, CreateTransaction, DepositRequestForm
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db.models import F,Q
from django.contrib.auth.models import User
from django.template import loader
import hashlib

class CreateAccountView(generic.CreateView):
    model = UserAccount
    template_name = 'AIUTS/account_form.html'    
    form_class = CreateAccount
  
    def form_valid(self, form):
        self.instance =form.save(commit=False)
        username = form.cleaned_data['username']
        accountId= hashlib.md5(str.encode(username)).hexdigest()
        user = User.objects.create_user(username=username,password=form.cleaned_data['password1'])
        user.save()
        acct = UserAccount(user=user, accountId =accountId, accountAmount=100 )
        acct.save()
        return redirect('AIUTS:index')

class CreateTransactionView(LoginRequiredMixin,generic.CreateView):
    login_url = '/accounts/login/'
    model = UserTransaction
    template_name = 'AIUTS/transaction_form.html'    
    form_class = CreateTransaction
    success_url ="/"
    def form_valid(self,form):
        self.instance =form.save(commit=False)
        form.instance.user = self.request.user
        transactionReceiver = self.request.POST.get('transactionReceiver')
        transactionAmount = form.cleaned_data['transactionAmount']
        transactionMessage =self.request.POST.get('transactionMessage')
        
        #user = UserAccount.objects.get(user=self.request.user)
        sender = UserAccount.objects.get(user=self.request.user)
        receiver = UserAccount.objects.get(pk=transactionReceiver)
        transaction =UserTransaction(
            transactionSender=sender, 
            transactionReceiver=receiver, 
            transactionAmount=transactionAmount, 
            transactionMessage=transactionMessage,
            transactionStatus='Approve'
            )
        transaction.save()
        
        if transactionAmount>sender.accountAmount:
            messages.warning(self.request, "Your transaction was unsuccessfull,please top up")
            return redirect('AIUTS:addTransaction')
        elif sender == receiver:
            messages.warning(self.request, "Your transaction was unsuccessfull, please Try again")
            return redirect('AIUTS:addTransaction')
        #return super().form_valid(form)
        return redirect('AIUTS:index')
    
class userAccountList(LoginRequiredMixin,generic.ListView):
    login_url = '/accounts/login/'
    template_name = 'AIUTS/index.html'
    context_object_name = 'users'
    def get_queryset(self):
        return UserAccount.objects.filter(user=self.request.user)

class userbalanceView(LoginRequiredMixin,generic.DetailView):
    login_url = '/accounts/login/'
    model = UserAccount
    template_name = 'AIUTS/balance.html'

class transactionList(LoginRequiredMixin,generic.ListView):
    login_url = '/accounts/login/'
    template_name = 'AIUTS/transactionList.html'
    context_object_name = 'transactions'
    
    def post(self, request):
        user = UserAccount.objects.get(user=request.user)
        from_date = self.request.POST['from_date']
        to_date = self.request.POST['to_date']
        template = loader.get_template(self.template_name)

        transactions = UserTransaction.objects.filter(Q(transactionSender=user) & Q(transactionStatus='Approve') | Q(transactionReceiver=user)& Q(transactionStatus='Approve')).order_by('-transactionTime')

        if len(from_date) and len(to_date):
            from_date = datetime.strptime(from_date, '%Y-%m-%d')
            to_date = datetime.strptime(to_date, '%Y-%m-%d') + timedelta(days=1)
            transactions =  UserTransaction.objects.filter(Q(transactionSender=user) & Q(transactionStatus='Approve') & Q(transactionTime__range=(from_date,to_date)) | Q(transactionReceiver=user) & Q(transactionStatus='Approve') & Q(transactionTime__range=(from_date,to_date))) .order_by('-transactionTime')
        
        context = {"transactions": transactions, "Reset":True}
        return HttpResponse(template.render(context, request))
    def get_queryset(self):
        user = UserAccount.objects.get(user=self.request.user)
        return  UserTransaction.objects.filter(Q(transactionSender=user) & Q(transactionStatus='Approve') | Q(transactionReceiver=user) & Q(transactionStatus='Approve')).order_by('-transactionTime')
 
class requestList(LoginRequiredMixin,generic.ListView):
    login_url = '/accounts/login/'
    template_name = 'AIUTS/requestList.html'
    context_object_name = 'requestTransactions'
    def get_queryset(self):
        user = UserAccount.objects.get(user=self.request.user)
        return  UserTransaction.objects.filter(Q(transactionSender=user) & Q(transactionStatus="Pending")).order_by('-transactionTime')

class pendingList(LoginRequiredMixin,generic.ListView):
    login_url = '/accounts/login/'
    template_name = 'AIUTS/transactionStatus.html'
    context_object_name = 'Ptransactions'
    def get_queryset(self):
        user = UserAccount.objects.get(user=self.request.user)
        return  UserTransaction.objects.filter(Q(transactionSender=user)  & Q(transactionStatus="Pending") | Q(transactionReceiver=user) & Q(transactionStatus="Pending")).order_by('-transactionTime')

class Approve(LoginRequiredMixin,generic.UpdateView):
    login_url = '/accounts/login/'
    model = UserTransaction
    fields = ['transactionStatus']
    template_name = 'AIUTS/edit.html'
    success_url = '/pendingList/'

class makeDeposit(LoginRequiredMixin,generic.CreateView):
    login_url = '/accounts/login/'
    model = DepositRequest
    template_name = 'AIUTS/requestDeposit.html'    
    form_class = DepositRequestForm
    success_url ="/"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        emp = User.objects.filter(groups__name='AIUTS_EMP')
        context["AIUTS_EMP"] = UserAccount.objects.filter(user__in=emp) 
        return context

    def form_valid(self,form):
        self.instance =form.save(commit=False)
        form.instance.user = self.request.user
        RequestAmount = form.cleaned_data['RequestAmount']
        RequestReceiver = UserAccount.objects.get(user=self.request.user)
        deposit =DepositRequest(RequestReceiver=RequestReceiver, RequestAmount =RequestAmount )
        deposit.save()
        return redirect('AIUTS:index')
    
class makeRequest(LoginRequiredMixin,generic.TemplateView):
    login_url = '/accounts/login/'
    template_name = 'AIUTS/requestPayment.html'
    
    def post(self, request):
        requestAmount = self.request.POST.get('depositAmount')
        requestRecipient = self.request.POST.get('requestRecipient')
        requestAmount=  self.request.POST.get('requestAmount')
        requestMessage = self.request.POST.get('transactionMessage')
        sender = UserAccount.objects.get(user=self.request.user).accountId

        if len(requestRecipient) and requestRecipient != sender:
            recipient = UserAccount.objects.get(user=self.request.user)
            sender = UserAccount.objects.get(pk=requestRecipient)
            UserRequest = UserTransaction(transactionSender=sender, transactionReceiver=recipient, transactionAmount=requestAmount,transactionStatus='Pending',transactionMessage=requestMessage,)
            UserRequest.save()
            return redirect('AIUTS:index')
            
        messages.warning(self.request, "Your request was unsuccessfull, please Try again")
        return redirect('AIUTS:paymentRequest')


       

AIUTS/templates/AIUTS/account_form.html
<html>

<head>
  {% load static %}
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="stylesheet" type="text/css" href="{% static 'AIUTS/login.css' %}">
  <title>Sign in</title>
</head>

<body>
<div class="main">
    <p class="sign">AIUTS | Sign Up</p>
    <form class="form1" method="POST" action="{% url 'AIUTS:addAccount' %}">

      {% csrf_token %}

    <label class="Lform" for="username">Username</label>
      <input class="un " type="text" placeholder="Username" name="username">
      <label class="Lform" for="password">Password</label>
      <input class="pass" type="password"  placeholder="password" name="password1">
      <label class="Lform" for="password">Confirm Password</label>
      <input class="pass" type="password"  placeholder="password" name="password2"> 


      <!-- <label class="Lform" for="accountAmount">Starting Amount</label>
      <input class="pass" type="number" placeholder="default amount is 100" value="100" name="accountAmount"> -->

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
        <ul class="errorlist"> 
          <li class="formError">{{ error|escape }}</li> 
        </ul>
          
        {% endfor %}
    {% endfor %}
{% endif %}
    
     <input class="submit" type="submit" value="Sign Up" />
    
      <p class="forgot" >Already have an account? <a class="createA"href="{% url 'login' %}">Sign In</p>

    </form>          
  </div>  
<!--  <div class="main">
    <form method="POST" action="{% url 'AIUTS:addAccount' %}" >
        {% csrf_token %}
    {{ form.as_p}} 



    {% if form.errors %}
      {% for field in form %}

           {% for error in field.errors %}
                {{field.label}}: {{ error|escape }}
           {% endfor %}

      {% endfor %}
{% endif %}

        <input type="submit" value="Create New Account">
    </form>  -->
</div>
</body>
</html>




















<!--  
{% block heading %}Creating Account{% endblock heading %}

{% block content %} 
<div class="form">
    <form method="POST" action="{% url 'AIUTS:addAccount' %}" >
        {% csrf_token %}
    {{ form.as_p}} 
        <input type="submit" value="Create New Account">
    </form>
</div>

{% endblock content %}  
 -->







  


<!-- <h1>Welcome to AIUTS</h1>

<form method="post" action="{% url 'login' %}" class="loginForm">
{% csrf_token %}

  <label for="username">Username: </label>
  <input type="text" name="username"> <br>

  <label for="password">Password: </label>
  <input type="password" name="password"><br>

  <input type="submit" value="login" />
  <input type="hidden" name="next" value="{{ next }}" />
</form> -->


































































<!-- 
<html>

<head>
  {% load static %}
  <link rel="stylesheet" href="css/style.css">
  <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="stylesheet" type="text/css" href="{% static 'AIUTS/login.css' %}">
  <title>Sign Up</title>
</head>

<body>

 

  <div class="main">
    <p class="sign">AIUTS | Sign up</p>
    <form class="form1" method="post" action="{% url 'AIUTS:addAccount' %}">
      {% csrf_token %}
      <input class="un " type="text" placeholder="Username" name="username">
      <input class="un " type="text" placeholder="Username" name="password">
      <input class="un " type="num" placeholder="Username" name="accountAmount">

     <input class="submit" type="submit" value="Create Account" />
    
      <p class="forgot" >Already have an account? <a class="createA"href="{% url 'login' %}">Login</p>

    </form>          
  </div>  
</body>
</html>

 -->

AIUTS/templates/AIUTS/edit.html
<style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@200&display=swap');
html {
    font-family: 'Poppins', sans-serif;
    position: relative;
    width: 100%;
    height: 100vh;
}

form {
    position: absolute;
    top: 20%;
    left: 800px;
}

h1 {
    text-transform: uppercase;
}

select {
    width: 100px;
    height: 35px;
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
    border: none;
}

button {
    background-color: #d47304;
    width: 100px;
    height: 35px;
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
    border: none;
    animation: background-color 0.3s;
}

button:hover {
    background-color: #6bff39;
}


</style>
<form method="post" >
    
    {% csrf_token %}
    <h1>{{ form.as_p }}</h1>

    <div>
        <button  type="submit">Save</button><br>
    </div>  
    
</form>

AIUTS/templates/AIUTS/index.html
{% extends "AIUTS/template.html" %}



{% block heading %}


{% if users %}
    {% for user in users %}
        <p>Balance: {{user.accountAmount}} Baht</p>
    {% endfor %}
    {% else %}
    <p> No Account are available. </p>
    {% endif %}
{% endblock heading %}

{% block content %} 
    <p>username:  {{ user }}</p>
    {% if users %}
            {% for user in users %}
                <p>Account ID: {{ user.accountId }} </p>
            {% endfor %}

        {% else %}
        <p> No Account are available. </p>
    {% endif %}
    <hr /> </br>
    <div class="navbuttons">
        <button class="btnMain"><a href="{% url 'AIUTS:deposit' %}" >Deposit Money</a></button>
        <button class="btnMain"><a href="{% url 'AIUTS:addTransaction' %}" >Make Transaction</a></button>
        <button class="btnMain"><a href="{% url 'AIUTS:paymentRequest' %}" >Payment Request</a></button>

    </div>
    
    
{% endblock content %}

AIUTS/templates/AIUTS/requestDeposit.html
{% extends "AIUTS/template.html" %}
{% block title %} Back {% endblock title %}
{% block heading %}Making Deposit{% endblock heading %}
{% block content %} 


<form action="{% url 'AIUTS:deposit' %}" method="POST">
    {% csrf_token %}
    <label>Deposit Amount</label>
    <input type="number" name="RequestAmount" min="1">
    <input type="submit"> 
</form>

{% endblock content %}

AIUTS/templates/AIUTS/requestList.html
{% extends "AIUTS/template.html" %}
{% block title %}Back{% endblock title %}
{% block heading %}Pending Request{% endblock heading %}
{% block content %} 



<table class="styled-table">
    <thead>
        <tr>
            <th>From</th>
            <th>Amount</th>
            <th>Status</th>
            <th>Note</th>
            <th>Date</th>
            <th></th>
            <th></th>
          
        </tr>
    </thead>
    
    <tbody>
        {% for transaction in requestTransactions %}
        <tr>
            <td>{{ transaction.transactionReceiver.user.username |capfirst}}</td>
            <td>{{ transaction.transactionAmount }} baht</td>
            <td>{{ transaction.transactionStatus}}</td>
            <td>{{ transaction.transactionMessage }}</td>
            <td>{{ transaction.transactionTime|date:"M d, Y" }}</td>
            {% if transaction.transactionSender.user.username == request.user.username %} 
            <td> <button> <a > Approve </a></button></td>
            <td> <button> <a > Decline </a></button></td>
            {% endif %}

        </tr>
        


    </tbody>
   
        <td>
            {% empty %}
            <p>You don't have any pending request</p>
        {% endfor %}
        </td>

    
</table>


{% endblock content %}

AIUTS/templates/AIUTS/requestPayment.html
{% extends "AIUTS/template.html" %}
{% block title %} Back {% endblock title %}
{% block heading %}Requesting Payment{% endblock heading %}
{% block content %} 


    <form action="{% url 'AIUTS:paymentRequest' %}" method="POST">
        {% csrf_token %}
        <label >Request Payment From:</label>
        <input type="text" name="requestRecipient" size="40>
        <label >Request Amount:</label>
        <input type="number" name="requestAmount">
        <label >Request Message:</label>
        <input type="text" name="transactionMessage">
        <input type="submit">
    </form>

{% endblock content %}

AIUTS/templates/AIUTS/template.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'AIUTS/styles.css' %}">
    <title> AIUTS </title>
</head>
<body>
    <p class="logout">{{user}} &nbsp;|&nbsp; <a class="logoutbtn" href="{% url 'logout'%}">Logout</a></p>
    <header>
            <h1 class="logo"><a class="logo-name"href="{% url 'AIUTS:index' %}" >{% block title %}AIUTS{% endblock title %}</a></h1>
            <h2 class="section-name">{% block heading %}{% endblock heading %}</h2>
            <nav>
                <ul>
                    <li><a href="{% url 'AIUTS:transactionList' %}" >Transaction Summary</a></li>
                    <hr>
                    <li><a href="{% url 'AIUTS:pendingList' %}" >Pending Request</a></li>
                </ul>
            </nav>
      
    </header>
    
    <div id="main">
        {% block content %} 

        {% if messages %}
            {% for message in messages %}
                <div >
                    {{ message}}
                </div>
            {% endfor %}
    {% endif %}
        {% endblock content %}  
    </div>
    <footer>Created by group 4 | April 6, 2021</footer>














</body>
</html>

AIUTS/templates/AIUTS/transactionList.html
{% extends "AIUTS/template.html" %}
{% block title %}Back{% endblock title %}
{% block heading %}Transaction History{% endblock heading %}
{% block content %} 

<fieldset>
    <legend>Filter Transaction History:</legend>
    <form  method="POST">
        {% csrf_token %}
        <label class="from_date_label" for="from_date">From:</label>
        <input class="from_date" type="date"  name="from_date">

        <label class="from_date_label" for="to_date">To:</label>
        <input type="date"  name="to_date">
 
        <button type="submit">{% if Reset %} RESET {% else %} Filter{% endif %}</button>
    </form>
  </fieldset>

<table class="styled-table">
    <thead>
        <tr>
            <th>#</th>
            <th>Sender</th>
            <th>Receiver</th>
            <th>Amount</th>
            <th>Note</th>
            <th>Date</th>
       
        </tr>
    </thead>
    
    <tbody>
        
        {% for transaction in transactions %}
           
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>
                {% if transaction.transactionSender.user.username == request.user.username %} 
                {{transaction.transactionSender.user.username}} (You)   
                {% else %}
                {{ transaction.transactionSender.user.username }}
                {% endif %}
            </td>
            <td>
                {% if transaction.transactionReceiver.user.username == request.user.username %} 
                You   
                {% else %}
                {{ transaction.transactionReceiver.user.username }}
                {% endif %}
            </td>
            <td>{{ transaction.transactionAmount }} baht</td>
            <td>{{ transaction.transactionMessage }}</td>
            <td>{{ transaction.transactionTime|date:"M d, Y" }}</td>
           
        </tr>
        {% empty %}
        <p>No transactions</p>
    {% endfor %}
    </tbody>
    
</table>


{% endblock content %}

AIUTS/templates/AIUTS/transactionStatus.html
{% extends "AIUTS/template.html" %}
{% block title %}Back{% endblock title %}
{% block heading %}Pending Request{% endblock heading %}
{% block content %} 



<table class="styled-table">
    <thead>
        <tr>
            <th>#</th>
            <th>From</th>
            <th>Amount</th>
            <th>Note</th>
            <th>Date</th>
            <th>Status</th>
            <th></th>
          
        </tr>
    </thead>
    
    <tbody>
        {% for transaction in Ptransactions %}
        <tr>
           
            <td>{{ forloop.counter }}</td>
            <td>
                {% if transaction.transactionReceiver.user.username == request.user.username %} 
                {{ transaction.transactionReceiver.user.username |capfirst}} (You)   
                {% else %}
                {{ transaction.transactionReceiver.user.username |capfirst}}
                {% endif %}
            </td>
            <td>{{ transaction.transactionAmount }} baht</td>
            <td>{{ transaction.transactionMessage }}</td>
            <td>{{ transaction.transactionTime|date:"M d, Y" }}</td>
            <td>{{ transaction.transactionStatus }}</td>

            {% if transaction.transactionSender.user.username == request.user.username %}
            <td>
               <button> <a  href="{% url 'AIUTS:Approve' transaction.transactionId%}" >Approve</a></button> 
            </td>
            {% endif %}

        </tr>
        


    </tbody>
   
        <td>
            {% empty %}
            <p>You don't have any pending request</p>
        {% endfor %}
        </td>

    
</table>


{% endblock content %}

AIUTS/templates/AIUTS/transaction_form.html
{% extends "AIUTS/template.html" %}
{% block title %} Back {% endblock title %}
{% block heading %}Making Transaction {% endblock heading %}


{% block content %} 
{% for message in messages %}
<div role="alert" class="msg">
 <p>{{ message }}</p> 
</div>
{% endfor %}

    <form method="POST" action="{% url 'AIUTS:addTransaction' %}" >
    {% csrf_token %}
    <!-- {{ form.as_p}}  -->
     <!-- <label for="transactionSender">From:</label>
    <input  type="text" name="transactionSender" ><br> -->

    <label for="transactionReceiver">Send To: </label>
    <input  type="text" name="transactionReceiver" size="40>

    <label for="transactionAmount">Amount: </label>
    <input type="number" name="transactionAmount" placeholder="0">

    <label for="transactionMessage">Message: </label>
    <input type="text" name="transactionMessage" placeholder="short note">

   

    <input type="submit" value="Make Transaction"> 
   
</div>
{% endblock content %}